// <auto-generated />
namespace DatabaseMigration.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removegenderfromEmployeeTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removegenderfromEmployeeTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202006211542414_remove gender from Employee Table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
